### ISSUE TITLE
[FEAT]: ansible-galaxy usage of git+ssh instead of git+https

### ISSUE THREAD

**Issue by Schroeffu** [projectpotos/ansible-specs-potos#8]
### Description

It should be possible to use Git Repositoris with SSH + SSH Key instead of only HTTPS

Before:
```
- name: wallpaper
  src: git+https://github.com/projectpotos/ansible-role-potos_wallpaper.git
  version: 'main'
```
Wish:
```
- name: wallpaper
  src: git+ssh://mytool.xyz/myproject/ansible-role-potos_wallpaper.git
  version: 'main'
```
  

### Additional Information

afaik, ansible-galaxy uses ssh-agent by default

**Comment by fadnincx** [comment]
According to the [galaxy documentation](https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file) the format would probably be:
```
- name: wallpaper
  src: git@mytool.xyz/myproject/ansible-role-potos_wallpaper.git
  scm: git
  version: "main"
```

**Comment by fadnincx** [comment]
Bigger issue is, how to ensure no interactive input is needed to accept hostkeys, or how we could allow for custom ssh options

**Comment by fadnincx** [comment]
An example on how to use it with [#10](https://github.com/projectpotos/ansible-plays-potos/pull/10)

```
- name: wallpaper
  src: git@github.com/fadnincx/ansible-role-private_wallpaper.git
  scm: git
  version: "main"
  key_file: "{{ playbook_dir }}/github.rsa"
```
When the file is placed in this repo under `/files/github.rsa`. Ensure it has permissions 0600, else ssh will not use this private key! 

The `key_file` needs to be an absolute path! 
You can additionally specify the value `ssh_opts` with arbitrary ssh options, but be careful as this is a quite powerful option
